
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Nov  3 2023 10:12:30 IST (Nov  3 2023 04:42:30 UTC)

// Verification Directory fv/top 

module top(clk, reset, WriteData, DataAdr, MemWrite);
  input clk, reset;
  output [31:0] WriteData, DataAdr;
  output MemWrite;
  wire clk, reset;
  wire [31:0] WriteData, DataAdr;
  wire MemWrite;
  assign MemWrite = 1'b0;
  assign DataAdr[0] = 1'b0;
  assign DataAdr[1] = 1'b0;
  assign DataAdr[2] = 1'b0;
  assign DataAdr[3] = 1'b0;
  assign DataAdr[4] = 1'b0;
  assign DataAdr[5] = 1'b0;
  assign DataAdr[6] = 1'b0;
  assign DataAdr[7] = 1'b0;
  assign DataAdr[8] = 1'b0;
  assign DataAdr[9] = 1'b0;
  assign DataAdr[10] = 1'b0;
  assign DataAdr[11] = 1'b0;
  assign DataAdr[12] = 1'b0;
  assign DataAdr[13] = 1'b0;
  assign DataAdr[14] = 1'b0;
  assign DataAdr[15] = 1'b0;
  assign DataAdr[16] = 1'b0;
  assign DataAdr[17] = 1'b0;
  assign DataAdr[18] = 1'b0;
  assign DataAdr[19] = 1'b0;
  assign DataAdr[20] = 1'b0;
  assign DataAdr[21] = 1'b0;
  assign DataAdr[22] = 1'b0;
  assign DataAdr[23] = 1'b0;
  assign DataAdr[24] = 1'b0;
  assign DataAdr[25] = 1'b0;
  assign DataAdr[26] = 1'b0;
  assign DataAdr[27] = 1'b0;
  assign DataAdr[28] = 1'b0;
  assign DataAdr[29] = 1'b0;
  assign DataAdr[30] = 1'b0;
  assign DataAdr[31] = 1'b0;
  assign WriteData[0] = 1'b0;
  assign WriteData[1] = 1'b0;
  assign WriteData[2] = 1'b0;
  assign WriteData[3] = 1'b0;
  assign WriteData[4] = 1'b0;
  assign WriteData[5] = 1'b0;
  assign WriteData[6] = 1'b0;
  assign WriteData[7] = 1'b0;
  assign WriteData[8] = 1'b0;
  assign WriteData[9] = 1'b0;
  assign WriteData[10] = 1'b0;
  assign WriteData[11] = 1'b0;
  assign WriteData[12] = 1'b0;
  assign WriteData[13] = 1'b0;
  assign WriteData[14] = 1'b0;
  assign WriteData[15] = 1'b0;
  assign WriteData[16] = 1'b0;
  assign WriteData[17] = 1'b0;
  assign WriteData[18] = 1'b0;
  assign WriteData[19] = 1'b0;
  assign WriteData[20] = 1'b0;
  assign WriteData[21] = 1'b0;
  assign WriteData[22] = 1'b0;
  assign WriteData[23] = 1'b0;
  assign WriteData[24] = 1'b0;
  assign WriteData[25] = 1'b0;
  assign WriteData[26] = 1'b0;
  assign WriteData[27] = 1'b0;
  assign WriteData[28] = 1'b0;
  assign WriteData[29] = 1'b0;
  assign WriteData[30] = 1'b0;
  assign WriteData[31] = 1'b0;
endmodule

